import { useState, useEffect } from 'react'

function App() {
  const [apiMessage, setApiMessage] = useState('Loading...')

  useEffect(() => {
    fetch('http://localhost:4000/')
      .then((res) => res.json())
      .then((data) => setApiMessage(data.message || 'Connected to backend!'))
      .catch((err) => setApiMessage('Failed to connect to backend on port 4000'))
  }, [])

  return (
    <div style={{ padding: '2rem', fontFamily: 'sans-serif', maxWidth: '600px', margin: '0 auto', textAlign: 'center' }}>
      <h1>Welcome to {{projectName}}</h1>
      <p style={{ color: '#666' }}>Generated by Forge-Gen</p>
      
      <div style={{ marginTop: '2rem', padding: '1.5rem', border: '1px solid #eaeaea', borderRadius: '10px', backgroundColor: '#fafafa' }}>
        <h2 style={{ fontSize: '1.2rem', marginBottom: '1rem' }}>Backend Connection Status</h2>
        <div style={{ padding: '1rem', backgroundColor: '#fff', borderRadius: '5px', fontWeight: 'bold', color: apiMessage.includes('Failed') ? '#e74c3c' : '#2ecc71' }}>
          {apiMessage}
        </div>
      </div>
    </div>
  )
}

export default App
